export const homeContent = {
    en: {
        nav: { home: 'Home', about: 'About', projects: 'Projects', contact: 'Contact' },
        hero: {
            title: 'Irfan Hariyanto — Graphic Designer & WhatsApp Bot Developer',
            badge: 'Selected Work',
            subtitle: 'Building a personal identity with warm neo style, calm content structure, and professional presentation of work.',
            seeProjects: 'See Projects',
            contact: 'Contact',
        },
        about: {
            small: 'About Me',
            title: 'I Learn Through Experiences',
            p1: "I’m Irfan, from Indonesia. I’ve spent my time to take any opportunity as well as developing my experience and skills to things like Graphic Designing, Programming, and many others.",
            p2: "But one thing I always stick with everything is, I always do every works as my passion, and that's what makes me happy also giving myself a chance to deliver best works that i can do.",
        },
        education: { small: 'Education', title: 'Educational Timeline', badge: 'Growth & Experience' },
        projectsHeading: { small: 'Selected Projects', title: 'Projects that showcase visual and technical quality.', viewAll: 'View all Projects' },
        contact: { small: 'Contact', title: 'Get in touch to discuss projects or collaborations.', emailCTA: 'Email' },
        footer: { text: 'Design, web, photo, and video for strong personal brands.', backToTop: 'Back to top', copyright: '© 2026 Irfan Hariyanto. All rights reserved.' },
        brand: { small: 'Portfolio' },
        preview: {
            preview: 'Preview',
            modern: 'Modern Portfolio',
            portfolioLabel: 'Portfolio',
            liveLabel: 'Live',
            desc: 'Website, photo, and video — composed to present a clear, elegant brand.',
            terminalLines: [
                'npm run start — serving portfolio…',
                '→ initializing layout: neo-warm theme',
                '→ loading assets: images, fonts, motion',
                'build complete — visit /projects to explore',
            ],
        },
        stats: { experience: 'Experience', focus: 'Focus', experienceValue: '4+ Years', focusValue: 'Personal Brand' },
        contactCard: { emailLabel: 'Email', instagramLabel: 'Instagram', githubLabel: 'Github' },
        skillsHeading: { small: 'Skills', title: 'Technical Skills' },
        skills: [
            { key: 'javascript', label: 'JavaScript', iconLight: '/icons/javascript.svg', iconDark: '/icons/javascript.svg', color: 'bg-[#f0db4f]' },
            { key: 'typescript', label: 'TypeScript', iconLight: '/icons/typescript.svg', iconDark: '/icons/typescript.svg', color: 'bg-[#2f74c0]' },
            { key: 'csharp', label: 'C#', iconLight: '/icons/csharp.svg', iconDark: '/icons/csharp.svg', color: 'bg-[#178600]' },
            { key: 'nodejs', label: 'NodeJS', iconLight: '/icons/nodejs.svg', iconDark: '/icons/nodejs.svg', color: 'bg-[#3c873a]' },
            { key: 'mysql', label: 'MySQL', iconLight: '/icons/mysql.svg', iconDark: '/icons/mysql.svg', color: 'bg-[#00758f]' },
            { key: 'xampp', label: 'XAMPP', iconLight: '/icons/xampp.svg', iconDark: '/icons/xampp.svg', color: 'bg-[#f26d21]' },
            { key: 'git', label: 'Git', iconLight: '/icons/git.svg', iconDark: '/icons/git.svg', color: 'bg-[#f05032]' },
            { key: 'vscode', label: 'VS Code', iconLight: '/icons/vscode.svg', iconDark: '/icons/vscode.svg', color: 'bg-[#0078d7]' },
            { key: 'figma', label: 'Figma', iconLight: '/icons/figma.svg', iconDark: '/icons/figma.svg', color: 'bg-[#a259ff]' },
            { key: 'github', label: 'GitHub', iconLight: '/icons/github-light.svg', iconDark: '/icons/github-dark.svg', color: 'bg-[#24292f]' },
            { key: 'github-copilot', label: 'GitHub Copilot', iconLight: '/icons/github-copilot-light.svg', iconDark: '/icons/github-copilot-dark.svg', color: 'bg-[#04a27a]' },
            { key: 'canva', label: 'Canva', iconLight: '/icons/canva.svg', iconDark: '/icons/canva.svg', color: 'bg-[#00c4ff]' },
            { key: 'photoshop', label: 'Adobe Photoshop', iconLight: '/icons/photoshop.svg', iconDark: '/icons/photoshop.svg', color: 'bg-[#001e36]' },
            { key: 'premiere', label: 'Adobe Premiere', iconLight: '/icons/premiere.svg', iconDark: '/icons/premiere.svg', color: 'bg-[#2b0f6a]' },
            { key: 'illustrator', label: 'Adobe Illustrator', iconLight: '/icons/illustrator.svg', iconDark: '/icons/illustrator.svg', color: 'bg-[#ff7b00]' },
            { key: 'coreldraw', label: 'Corel Draw', iconLight: '/icons/coreldraw.svg', iconDark: '/icons/coreldraw.svg', color: 'bg-[#d32f2f]' },
        ],
    },
    id: {
        nav: { home: 'Beranda', about: 'Tentang', projects: 'Projek', contact: 'Kontak' },
        hero: {
            title: 'Irfan Hariyanto — Desainer Grafis & WhatsApp Bot Developer',
            badge: 'Karya Terpilih',
            subtitle: 'Membangun identitas personal dengan gaya neo hangat, struktur konten yang tenang, dan presentasi karya yang profesional.',
            seeProjects: 'Lihat Projek',
            contact: 'Kontak',
        },
        about: {
            small: 'Tentang Saya',
            title: 'Saya Belajar dari Pengalaman',
            p1: 'Saya Irfan, dari Indonesia. Saya memanfaatkan setiap kesempatan untuk mengembangkan pengalaman dan keterampilan seperti Desain Grafis, Pemrograman, dan lain-lain.',
            p2: 'Namun satu hal yang selalu saya pegang adalah, saya melakukan setiap pekerjaan dengan penuh passion, dan itu membuat saya bahagia serta memberi kesempatan untuk memberikan hasil terbaik.',
        },
        education: { small: 'Pendidikan', title: 'Timeline Pendidikan', badge: 'Perkembangan & Pengalaman' },
        projectsHeading: { small: 'Proyek Terpilih', title: 'Proyek yang menunjukkan kualitas visual dan teknis.', viewAll: 'Lihat Semua Projek' },
        contact: { small: 'Kontak', title: 'Hubungi saya untuk membahas proyek atau kolaborasi.', emailCTA: 'Email' },
        footer: { text: 'Desain, web, foto, dan video untuk personal brand yang kuat.', backToTop: 'Kembali ke atas', copyright: '© 2026 Irfan Hariyanto. Semua hak dilindungi.' },
        brand: { small: 'Portofolio' },
        preview: {
            preview: 'Preview',
            modern: 'Modern Portfolio',
            portfolioLabel: 'Portfolio',
            liveLabel: 'Live',
            desc: 'Website, foto, dan video. Setiap elemen disusun untuk brand yang jelas dan elegan.',
            terminalLines: [
                'npm run start — memulai portfolio…',
                '→ inisialisasi layout: tema neo-hangat',
                '→ memuat aset: gambar, font, motion',
                'build selesai — lihat /projects untuk menjelajah',
            ],
        },
        stats: { experience: 'Pengalaman', focus: 'Fokus', experienceValue: '4+ Tahun', focusValue: 'Personal Brand' },
        contactCard: { emailLabel: 'Email', instagramLabel: 'Instagram', githubLabel: 'Github' },
        skillsHeading: { small: 'Keterampilan', title: 'Keahlian Teknis' },
        skills: [
            { key: 'javascript', label: 'JavaScript', iconLight: '/icons/javascript.svg', iconDark: '/icons/javascript.svg', color: 'bg-[#f0db4f]' },
            { key: 'typescript', label: 'TypeScript', iconLight: '/icons/typescript.svg', iconDark: '/icons/typescript.svg', color: 'bg-[#2f74c0]' },
            { key: 'csharp', label: 'C#', iconLight: '/icons/csharp.svg', iconDark: '/icons/csharp.svg', color: 'bg-[#178600]' },
            { key: 'nodejs', label: 'NodeJS', iconLight: '/icons/nodejs.svg', iconDark: '/icons/nodejs.svg', color: 'bg-[#3c873a]' },
            { key: 'mysql', label: 'MySQL', iconLight: '/icons/mysql.svg', iconDark: '/icons/mysql.svg', color: 'bg-[#00758f]' },
            { key: 'xampp', label: 'XAMPP', iconLight: '/icons/xampp.svg', iconDark: '/icons/xampp.svg', color: 'bg-[#f26d21]' },
            { key: 'git', label: 'Git', iconLight: '/icons/git.svg', iconDark: '/icons/git.svg', color: 'bg-[#f05032]' },
            { key: 'vscode', label: 'VS Code', iconLight: '/icons/vscode.svg', iconDark: '/icons/vscode.svg', color: 'bg-[#0078d7]' },
            { key: 'figma', label: 'Figma', iconLight: '/icons/figma.svg', iconDark: '/icons/figma.svg', color: 'bg-[#a259ff]' },
            { key: 'github', label: 'GitHub', iconLight: '/icons/github-light.svg', iconDark: '/icons/github-dark.svg', color: 'bg-[#24292f]' },
            { key: 'github-copilot', label: 'GitHub Copilot', iconLight: '/icons/github-copilot-light.svg', iconDark: '/icons/github-copilot-dark.svg', color: 'bg-[#04a27a]' },
            { key: 'canva', label: 'Canva', iconLight: '/icons/canva.svg', iconDark: '/icons/canva.svg', color: 'bg-[#00c4ff]' },
            { key: 'photoshop', label: 'Adobe Photoshop', iconLight: '/icons/photoshop.svg', iconDark: '/icons/photoshop.svg', color: 'bg-[#001e36]' },
            { key: 'premiere', label: 'Adobe Premiere', iconLight: '/icons/premiere.svg', iconDark: '/icons/premiere.svg', color: 'bg-[#2b0f6a]' },
            { key: 'illustrator', label: 'Adobe Illustrator', iconLight: '/icons/illustrator.svg', iconDark: '/icons/illustrator.svg', color: 'bg-[#ff7b00]' },
            { key: 'coreldraw', label: 'Corel Draw', iconLight: '/icons/coreldraw.svg', iconDark: '/icons/coreldraw.svg', color: 'bg-[#d32f2f]' },
        ],
    },
};

export const educationTimeline = {
    en: [
        { school: 'SD Negeri Marengan Laok 1', period: '2013 - 2019' },
        { school: 'SMP Negeri 5 Sumenep', period: '2019 - 2022' },
        { school: 'SMK Negeri 1 Kalianget (Desain Komunikasi Visual)', period: '2022 - 2025' },
        { school: 'Wiraraja University (Informatics Engineering)', period: '2025 - Now' },
    ],
    id: [
        { school: 'SD Negeri Marengan Laok 1', period: '2013 - 2019' },
        { school: 'SMP Negeri 5 Sumenep', period: '2019 - 2022' },
        { school: 'SMK Negeri 1 Kalianget (Desain Komunikasi Visual)', period: '2022 - 2025' },
        { school: 'Universitas Wiraraja (Teknik Informatika)', period: '2025 - Sekarang' },
    ],
};
